name: Terraform Deploy to Azure

on:
  workflow_dispatch:  
  push:
    branches:
      - main          

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Terraform Init
        working-directory: ./terraform_VM
        run: terraform init 
        

      - name: Terraform Plan
        working-directory: ./terraform_VM
        run: terraform plan 
        

      - name: Terraform Apply
        working-directory: ./terraform_VM
        run: terraform apply -auto-approve
        
