name: Terraform Deploy to Azure

on:
  workflow_dispatch:  
  push:
    branches:
      - main          

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform Init
        working-directory: ./terraform_VM
        run: terraform init -backend-config="storage_account_name=strdatablobci001" -backend-config="container_name=tfstate" -backend-config="resource_group_name=rg-test-ci-003"
        

      - name: Terraform Plan
        run: terraform plan 
        working-directory: ./terraform_VM

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform_VM
