name: Terraform Deploy to Azure

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:  
  push:
    branches:
      - main          

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0


      - name: Terraform Init
        working-directory: ./terraform_VM
        run: terraform init 
        

      - name: Terraform Plan
        working-directory: ./terraform_VM
        run: terraform plan 
        

      - name: Terraform Apply
        working-directory: ./terraform_VM
        run: terraform apply -auto-approve
        
